title: 9thinking Blog
description: Notes on coding, learning, and building in public.
theme: minima
url: "https://9thinking.github.io"
baseurl: "/skills-github-pages"
markdown: kramdown
show_excerpts: true
